language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

before_install:
  sudo apt-get install libogg-dev libvorbis-dev && cpanm -n Devel::Cover::Report::Coveralls
script:
  perl Makefile.PL && make && cover -test -report coveralls

after_failure:
  cat /home/travis/.cpanm/work/*/build.log
