name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        perl: [ 'latest' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: sudo apt-get update
      - run: sudo apt-get install libinline-perl libogg-dev libvorbis-dev
      - run: perl -V
      - run: cpanm --installdeps .
      - name: Archive CPAN logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: cpan_log
          path: /home/runner/.cpanm/work/*/build.log
      - run: prove -lv t

  coverage:
    runs-on: ubuntu-latest
    container: davorg/perl-coveralls:latest
    name: Test coverage
    steps:
      - uses: actions/checkout@v3
      - run: apt-get update
      - run: apt-get -y install libinline-perl libogg-dev libvorbis-dev
      - name: Install modules
        run: cpanm -n --installdeps .
      - name: Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cover -test -report Coveralls

  perlcritic:
    uses: PerlToolsTeam/github_workflows/.github/workflows/cpan-perlcritic.yml@main

  complexity:
    uses: PerlToolsTeam/github_workflows/.github/workflows/cpan-complexity.yml@main

